Add .ckpt name to output .yaml files
sd-webui/stable-diffusion-webui pull request #1196
Opened 2022-09-17 20:02 UTC by protoplm

Used loaded_model state variable as an argument for save_sample() calls and added a line to generated txt2img and img2img. Notably useful now that custom models can be switched in the UI. It uses the .ckpt name when custom variables are used, or "Stable Diffusion v1.4" if model.ckpt is.

# Checklist:

- [ ] I have changed the base branch to `dev`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2022-09-17 20:04 UTC, protoplm commented
> batch_size: 1
> cfg_scale: 7.5
> ddim_eta: 0.0
> ddim_steps: 30
> height: 512
> model_name: Stable Diffusion v1.4
> n_iter: 1
> normalize_prompt_weights: true
> prompt: a fish but better
> sampler_name: k_euler
> seed: 1079713602
> target: txt2img
> toggles:
> - 1
> - 2
> - 3
> - 4
> - 5
> width: 512
> 

> batch_size: 1
> cfg_scale: 7.5
> ddim_eta: 0.0
> ddim_steps: 30
> denoising_strength: '0.45'
> height: 512
> model_name: waifu-diffusion
> n_iter: 1
> normalize_prompt_weights: true
> prompt: a fish but even better
> resize_mode: 0
> sampler_name: k_euler
> seed: 2350937754
> target: img2img
> toggles:
> - 1
> - 2
> - 4
> - 5
> - 6
> - 7
> width: 512

2022-09-18 03:28 UTC, hlky requested changes

2022-09-18 03:28 UTC, hlky commented on scripts/sd_utils.py
> +                                seed=seeds[i], width=width, height=height, normalize_prompt_weights=normalize_prompt_weights, model_name=model_name)
This should be `model_name=st.session_state["loaded_model"]`

2022-09-18 03:28 UTC, hlky commented on scripts/sd_utils.py
> +                save_grid, sort_samples, sampler_name, ddim_eta, n_iter, batch_size, i, denoising_strength, resize_mode, save_individual_images, model_name):
This should be `model_name=st.session_state["loaded_model"]`

2022-09-18 09:34 UTC, merged